Refactor/questionnaire
alphayesodot/itur-client pull request #111
Opened 2021-08-08 12:00 UTC by lustigy96

2021-08-08 14:40 UTC, carmeltsadok requested changes

2021-08-08 14:40 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/SchemasTable/SchemasTable.jsx
> +    if (!rolesArr.includes('MALSHAB')) {
use `Role.Malshab`

2021-08-08 14:40 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/config.js
> +    max: { tag: '', value: 5 },
required ?!?!?!?!?!?!?!>1

2021-08-08 14:40 UTC, carmeltsadok commented on src/services/node.service.js
> +  }, { maxAge: 10000 });
add to appConf

2021-08-08 17:09 UTC, carmeltsadok requested changes

2021-08-08 17:09 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/SchemasTable/SchemasTable.jsx
> +      <div className={`${classes.root}`}>
```suggestion
      <div className={classes.root}>
```

2021-08-09 07:36 UTC, carmeltsadok approved these changes

2021-08-10 12:44 UTC, maykremer approved these changes

2021-08-10 12:45 UTC, merged