Nodes page
alphayesodot/itur-client pull request #116
Opened 2021-08-10 11:21 UTC by lihi2910

add node page

2021-08-10 12:02 UTC, maykremer requested changes

2021-08-10 12:02 UTC, maykremer commented on mockserver/index.js
> +    apiUri: `http://localhost:7071`,
```suggestion
    apiUri: `http://localhost:${config.port}`,
```

2021-08-10 12:27 UTC, maykremer requested changes

2021-08-10 12:27 UTC, maykremer commented on mockserver/node/db.js
> +  // {
remove comments

2021-08-10 12:27 UTC, maykremer commented on mockserver/node/node.manager.js
> +    if ([Role.Technical].includes(requester.role) && req.body.name) {
check `req.body.id` too because it is also required

2021-08-10 12:27 UTC, maykremer commented on mockserver/node/node.manager.js
> +    if ([Role.Technical].includes(requester.role) || !req.body.name) {
```suggestion
    if ([Role.Technical].includes(requester.role)) {
```

2021-08-10 12:27 UTC, maykremer commented on src/common/NodeHeader/NodeHeader.jsx
> +// import searchImg from '../../../../utils/images/general/search-yellow.svg';
```suggestion
```

2021-08-10 12:27 UTC, maykremer commented on src/common/NodeHeader/NodeHeader.jsx
> +  console.log(allowNewNodeGroup);
```suggestion
```

2021-08-10 12:27 UTC, maykremer commented on src/common/NodeHeader/NodeHeader.jsx
> +const NodeHeader = ({ allNodeGroupRows, setNodeGroupRowsToShow, setOpenDialog, allowNewNodeGroup, isNodeOrNodeG }) => {
make component more generic (not only for node/ nodegroup) so it will be good for more objects.
change to : 
`allRows, setRowsToShow, setOpenDialog, allowNewObject, objectName`

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/NodeDeleteButton/NodeDeleteButton.jsx
> +  setNodeGroupToDelete,
change to `node` and `setNodeToDelete`

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/NodeDeleteButton/NodeDeleteButton.jsx
> +
maybe make it common

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
> +const NodeDialog = ({ open, onClose, currentNodeGroup, setNodeToAdd}) => {
change to `currentNode`

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
> +    }
```suggestion
    UnitService.getUnits().then((res) => {
      setUnits(res);
    }).catch(() => {
       toast(t('error.server'));
    });
```

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
> +    }
why there will be an error?

2021-08-10 12:27 UTC, maykremer commented on mockserver/node/node.manager.js
> +import { generateId } from '../utils.js';
You haven't used it

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/index.jsx
> +    console.log("delete");
```suggestion
```

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/index.jsx
> +  console.log(userRole);
```suggestion
```

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/index.jsx
> +
```suggestion
```

2021-08-10 12:27 UTC, maykremer commented on src/pages/AddNodes/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +const SelectCheckboxItem = ({ //enter to common
so enter it :)

2021-08-12 11:19 UTC, carmeltsadok approved these changes

2021-08-15 09:06 UTC, lustigy96 requested changes

2021-08-15 09:06 UTC, lustigy96 commented on src/pages/AddNodes/index.jsx
> +import { useTranslation } from 'react-i18next';
bug: (Im writing here but you should check this problem) hover on the deletion button is not so good, you should cancel the hover and use hand pointer only (look at my code I have done this)

2021-08-15 13:46 UTC, lustigy96 approved these changes

2021-08-15 14:11 UTC, merged