feat: Add questionnaire report mock
alphayesodot/itur-client pull request #117
Opened 2021-08-10 13:46 UTC by carmeltsadok

2021-08-11 09:53 UTC, PCOffline requested changes

2021-08-11 09:53 UTC, PCOffline commented on mockserver/report/report.manager.js
> +  static async createQuestionnaireReport(_req, res) {
Remove useless async
```suggestion
  static createQuestionnaireReport(_req, res) {
```

2021-08-11 09:53 UTC, PCOffline commented on src/pages/Reports/components/EventsInputs/EventsInputs.jsx
> +      !(nodeGroupsRequiredRoles.includes(currentUser.role) && !selectedNodeGroups.length),
Change to a more intuitive syntax
```suggestion
      !nodeGroupsRequiredRoles.includes(currentUser.role) || selectedNodeGroups.length,
```

2021-08-11 09:53 UTC, PCOffline commented on src/pages/Reports/components/QuestionnaireInputs/QuestionnaireInputs.jsx
> +      !(nodeGroupsRequiredRoles.includes(currentUser.role) && !selectedNodeGroup)
Change to a more intuitive syntax
```suggestion
      !nodeGroupsRequiredRoles.includes(currentUser.role) || selectedNodeGroup
```

2021-08-12 07:01 UTC, carmeltsadok commented on src/pages/Reports/components/EventsInputs/EventsInputs.jsx
> +      !(nodeGroupsRequiredRoles.includes(currentUser.role) && !selectedNodeGroups.length),
it is more readable that way

2021-08-12 07:01 UTC, carmeltsadok commented on src/pages/Reports/components/QuestionnaireInputs/QuestionnaireInputs.jsx
> +      !(nodeGroupsRequiredRoles.includes(currentUser.role) && !selectedNodeGroup)
it is more readable that way

2021-08-12 07:07 UTC, PCOffline approved these changes

2021-08-12 07:08 UTC, PCOffline commented on src/pages/Reports/components/QuestionnaireInputs/QuestionnaireInputs.jsx
> +      !(nodeGroupsRequiredRoles.includes(currentUser.role) && !selectedNodeGroup)
How?

2021-08-12 10:22 UTC, maykremer approved these changes

2021-08-12 11:24 UTC, merged