build: Add Basic Dockerfile for NGINX
alphayesodot/itur-client pull request #12
Opened 2021-04-19 11:27 UTC by PCOffline

2021-04-19 12:09 UTC, carmeltsadok requested changes
Add a copy of nginx configuration file.

2021-04-20 08:04 UTC, carmeltsadok requested changes
Add an nginx.conf file as well

2021-04-22 13:10 UTC, carmeltsadok requested changes

2021-04-22 13:10 UTC, carmeltsadok commented on nginx.conf
> +    index index.html index.html
```suggestion
    index index.html index.htm;
```

2021-04-22 13:10 UTC, carmeltsadok commented on Dockerfile
> +ENV NODE_ENV=production
It is not required when using tag prod

2021-04-22 14:22 UTC, PCOffline commented on Dockerfile
> +ENV NODE_ENV=production
As Yonatan said, it is to avoid installing devDependencies.

2021-04-25 14:31 UTC, PCOffline commented
@carmeltsadok ready for merge with dev

2021-04-26 05:42 UTC, carmeltsadok approved these changes

2021-04-26 07:29 UTC, merged