bugfix/preparation-kit
alphayesodot/itur-client pull request #122
Opened 2021-08-12 14:30 UTC by PCOffline

2021-08-15 12:13 UTC, PCOffline commented
Compatible with https://github.com/alphayesodot/itur-be-functionapp/pull/128

2021-08-15 13:23 UTC, carmeltsadok requested changes

2021-08-15 13:23 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +      <p>{documentMessage}</p>
use `NoObjectsToShow` component

2021-08-15 13:23 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +          {video ? <ReactPlayer url={video} className={classes.player} controls /> : <p>{videoMessage}</p>}
same

2021-08-15 13:45 UTC, lustigy96 requested changes

2021-08-15 13:45 UTC, lustigy96 commented on mockserver/preparationKit/preparationKit.manager.js
> +  static getSas(req, res) {
who is Sas? I want to get it too

2021-08-15 13:45 UTC, lustigy96 commented on mockserver/preparationKit/preparationKit.manager.js
> +  static getSas(req, res) {
write a comment to explain what Sas is and explain it's use

2021-08-15 13:45 UTC, lustigy96 commented on mockserver/preparationKit/preparationKit.manager.js
> +        res.send('https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4');
put this url in const under the name mp4_example

2021-08-15 13:45 UTC, lustigy96 commented on mockserver/preparationKit/preparationKit.manager.js
> +        res.send('https://file-examples-com.github.io/uploads/2017/10/file-sample_150kB.pdf');
put this url in const under the name pdf_example

2021-08-15 13:45 UTC, lustigy96 commented on src/services/preparationKit.service.js
> +
```suggestion
```

2021-08-17 08:21 UTC, Delitefully approved these changes

2021-08-17 11:09 UTC, carmeltsadok approved these changes

2021-08-17 11:38 UTC, merged