Feat: Jitsi video implemented in screen (todo: remove more actions on…
alphayesodot/itur-client pull request #123
Opened 2021-08-15 09:32 UTC by AdarPascal

… guest)

2021-08-15 13:16 UTC, carmeltsadok requested changes

2021-08-15 13:16 UTC, carmeltsadok commented on src/common/VideoConference/VideoConference.jsx
> +        } catch (err) {}
toast an error

2021-08-15 13:16 UTC, carmeltsadok commented on src/common/VideoConference/VideoConference.jsx
> +    };
add to styles file and use `className` property on the divs themselves

2021-08-15 13:16 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/Malshab.jsx
> +);
move to a new component

2021-08-16 11:43 UTC, carmeltsadok requested changes

2021-08-16 11:43 UTC, carmeltsadok commented on src/common/VideoConference/VideoConference.styles.js
> +  },
remove style and remove it from div

2021-08-16 11:43 UTC, carmeltsadok commented on src/common/VideoConference/VideoConference.jsx
> +        <div className={classes.containerStyle}>
isn't it a useless div?

2021-08-16 11:43 UTC, carmeltsadok commented on src/pages/InterviewDashboard/DisplayNamePick/DisplayNamePick.jsx
> +    <div style={{ display: 'grid', justifyContent: 'center' }}>
add a classname

2021-08-22 10:14 UTC, yubbi99 approved these changes

2021-08-22 10:14 UTC, carmeltsadok approved these changes

2021-08-22 10:17 UTC, merged