Fix/interview page layout
alphayesodot/itur-client pull request #124
Opened 2021-08-16 07:09 UTC by carmeltsadok

2021-08-16 07:56 UTC, Delitefully approved these changes

2021-08-16 07:56 UTC, Delitefully commented on src/pages/InterviewDashboard/components/Notesbox/Notesbox.styles.js
> +    height: '42.75rem !important',
can we avoid !important here?

2021-08-16 09:25 UTC, PCOffline requested changes

2021-08-16 09:25 UTC, PCOffline commented on src/pages/Luz/components/InterviewRaw/InterviewRaw.jsx
> +          {status !== 'BREAK' && (
Turn this into an enum or a const

2021-08-16 09:25 UTC, PCOffline commented on src/pages/Luz/components/InterviewRaw/InterviewRaw.jsx
> +            className={`${classes.button}`}
```suggestion
            className={classes.button}
```

2021-08-16 11:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/AmericanAnswer/AmericanAnswer.jsx
> +      {hasOther && (
it can be false either.
and if it is null or undefined it **shouldn't** render the component.

2021-08-16 12:02 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.jsx
> +        {question.required ? <span className={classes.required} title={t('question.required')}>*</span> : ''}
no

2021-08-16 12:02 UTC, carmeltsadok commented on src/common/Questionnaire/Questionnaire.jsx
> +            <span>{` (${t('unitControlPage.totalText')} ${questions.length})`}</span>
whyyyy

2021-08-17 11:51 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.jsx
> +        {question.required ? <span className={classes.required} title={t('question.required')}>*</span> : ''}
ahhahahaaaaa

2021-08-17 11:52 UTC, PCOffline approved these changes

2021-08-22 12:21 UTC, merged