Feat/xml upload page
alphayesodot/itur-client pull request #13
Opened 2021-04-21 08:19 UTC by lustigy96

2021-04-21 09:48 UTC, carmeltsadok requested changes

2021-04-21 10:38 UTC, carmeltsadok requested changes

2021-04-21 10:38 UTC, carmeltsadok commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +            file.size / 1000,
Calculate from const

2021-04-21 10:38 UTC, carmeltsadok commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +  const progressBox = (file) => (
Move to a new component

2021-04-21 12:40 UTC, lustigy96 commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.styles.js
> +  progressBarColor: {
why ? (talk)

2021-04-21 12:40 UTC, lustigy96 commented on src/pages/XmlUploadSite/components/DropZone/DropZone.jsx
> +        /* eslint-disable react/jsx-props-no-spreading */
let's work through this together

2021-04-21 13:37 UTC, lustigy96 commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +  const progressBox = (file) => (
Without it, the progressBoxes is really tiny, so I dont think that it is needed

2021-04-21 13:38 UTC, lustigy96 commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +            file.size / 1000,
why

2021-04-21 13:41 UTC, lustigy96 commented on src/theme.js
>    },
compare

2021-04-21 14:54 UTC, carmeltsadok commented on mockserver/index.js
> +app.use('/api/upload-xml-file', xmlRouter);
```suggestion
app.use('/api/xml-upload', xmlRouter);
```

2021-04-21 14:54 UTC, carmeltsadok commented on mockserver/index.js
> +app.use('/api/upload-xml-file', xmlRouter);
According to the api

2021-04-21 14:54 UTC, carmeltsadok commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +  const progressBox = (file) => (
It's more readable when it is separated into tiny files

2021-04-21 14:55 UTC, carmeltsadok commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +            file.size / 1000,
So we will get the file limit from the config server

2021-04-25 12:27 UTC, lustigy96 commented on src/pages/XmlUploadSite/components/ProgressBox/ProgressBoxes.jsx
> +            file.size / 1000,
We may get the file limit from a config server, but it is irrelevant to this calculation. This calculation is about the uploaded file. The size limit is defined somewhere else (in const :) and we can take it from a config server

2021-04-26 09:01 UTC, carmeltsadok requested changes

2021-04-26 11:22 UTC, carmeltsadok approved these changes

2021-04-26 11:22 UTC, merged