Feat/posh page
alphayesodot/itur-client pull request #142
Opened 2021-08-29 08:32 UTC by carmeltsadok

2021-08-29 08:45 UTC, PCOffline requested changes

2021-08-29 08:45 UTC, PCOffline commented on mockserver/nodeGroup/nodeGroup.manager.js
> +    : nodeGroups.filter((nodeGroup) => nodeGroup.unitId === requester.unitId);
Remove redundant code:

```suggestion
    const unitNodesGroup = nodeGroups.filter((nodeGroup) => nodeGroup.unitId === (unitId ?? requester.unitId) );
```

2021-08-29 08:45 UTC, PCOffline commented on src/common/ScheduleHeader/ScheduleHeader.styles.js
> +      margin: '0.2em 0 !important',
Try creating a more specific rule instead of using `!important`

2021-08-29 09:23 UTC, carmeltsadok commented on src/common/ScheduleHeader/ScheduleHeader.styles.js
> +      margin: '0.2em 0 !important',
it happened to me before.. I have to put the impotant for ut to work in all cases

2021-08-29 09:24 UTC, carmeltsadok commented on mockserver/nodeGroup/nodeGroup.manager.js
> +    : nodeGroups.filter((nodeGroup) => nodeGroup.unitId === requester.unitId);
it is mock. who cares?

2021-08-29 09:26 UTC, PCOffline approved these changes

2021-08-29 09:47 UTC, maykremer approved these changes

2021-08-29 10:21 UTC, Delitefully approved these changes

2021-08-31 10:14 UTC, PCOffline approved these changes

2021-08-31 13:34 UTC, merged