Fix/interview results
alphayesodot/itur-client pull request #147
Opened 2021-08-30 15:29 UTC by carmeltsadok

2021-08-31 09:56 UTC, PCOffline approved these changes

2021-08-31 09:56 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +  const updateNote = async () => EventService.addEventNote(event.id, note);
Remove redundant `async`

2021-08-31 13:55 UTC, carmeltsadok commented on src/pages/InterviewDashboard/index.jsx
> +  const updateNote = async () => EventService.addEventNote(event.id, note);
I want to it to be promise..

2021-08-31 15:02 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +  const updateNote = async () => EventService.addEventNote(event.id, note);
It returns the result of `addEventNode`, so it'll be a promise..

2021-08-31 15:08 UTC, PCOffline requested changes

2021-08-31 15:08 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +import { useState, useEffect } from 'react';
Add React import

2021-08-31 15:08 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +  }, [event]);
Split to methods to make code more readable

2021-08-31 15:08 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
>      await EventService.addEventNote(event.id, note)
Remove redundant async await and simply return the promise

2021-08-31 15:08 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +                setNote={(v) => setNote(v)}
```suggestion
                setNote={setNote}
```

2021-08-31 15:20 UTC, carmeltsadok commented on src/pages/InterviewDashboard/index.jsx
> +                setNote={(v) => setNote(v)}
This is a good thing to do with setState methods

2021-09-01 06:10 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +                setNote={(v) => setNote(v)}
No, it's the exact same code, just your version is longer and unnecessary

2021-09-01 07:41 UTC, PCOffline requested changes

2021-09-01 07:41 UTC, PCOffline commented on src/pages/InterviewDashboard/index.jsx
> +import { useState, useEffect } from 'react';
I meant this:
```suggestion
import React, { useState, useEffect } from 'react';
```

2021-09-01 08:01 UTC, carmeltsadok commented on src/pages/InterviewDashboard/index.jsx
> +import { useState, useEffect } from 'react';
I have done it

2021-09-01 08:09 UTC, PCOffline approved these changes

2021-09-01 08:09 UTC, PCOffline commented on mockserver/questionnaireInstance/questionnaireInstance.manager.js
> +  static async create(req, res) {
Remove redundant `async`

2021-09-01 08:44 UTC, Delitefully approved these changes

2021-09-01 08:45 UTC, merged