Feature/edit nodepage
alphayesodot/itur-client pull request #148
Opened 2021-08-31 09:58 UTC by lihi2910

2021-08-31 10:25 UTC, carmeltsadok requested changes

2021-08-31 10:25 UTC, carmeltsadok commented on src/common/EditDeleteOptionsButton/EditDeleteOptionsButton.jsx
> +    }
why there will be any error? it is just setting states

2021-08-31 10:25 UTC, carmeltsadok commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
> +    }
```suggestion
    startValues(currentNode || '');
```

2021-08-31 10:25 UTC, carmeltsadok commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
>    useEffect(async () => {
```suggestion
  useEffect(() => {
```

2021-08-31 10:25 UTC, carmeltsadok commented on src/pages/AddNodes/components/NodeDialog/NodeDialog.jsx
> +    setCheckedUnit(node ? node.unitId : '');
```suggestion
    setNameValue(node?.name || '');
    setIdValue(node?.id || '');
    setCheckedType(node?.type || '');
    setCheckedUnit(node?.unitId || '');
```

2021-08-31 10:25 UTC, carmeltsadok commented on src/pages/AddNodes/index.jsx
> +    return object ? object.name : '';
```suggestion
    return object?.name || '';
```

2021-08-31 10:25 UTC, carmeltsadok commented on src/services/node.service.js
> +  { id: invitationsType.CLASSIFIED, name: 'מסווג' },
add to i18n

2021-08-31 10:25 UTC, carmeltsadok commented on src/services/node.service.js
> +
```suggestion
```

2021-08-31 10:26 UTC, carmeltsadok requested changes

2021-08-31 10:26 UTC, carmeltsadok commented on src/common/OptionButton/OptionButton.jsx
>  import useStyles from './OpetionButton.styles';
change file name to `OptionButton.styles` instead of `OpetionButton.styles`

2021-08-31 10:30 UTC, carmeltsadok requested changes

2021-08-31 10:30 UTC, carmeltsadok commented on src/common/OptionButton/OptionButton.jsx
>        >
add class name with `backgroundColor: 'transparent'`

2021-08-31 13:55 UTC, lustigy96 requested changes

2021-08-31 13:55 UTC, lustigy96 commented on src/common/EditDeleteOptionsButton/EditDeleteOptionsButton.jsx
> +  allowedUser,
It is better to make allowedUser as array, "allowedUsers" to make it more generic

2021-08-31 13:55 UTC, lustigy96 commented on src/common/OptionButton/OptionButton.jsx
> -        style={{ backgroundColor: 'transparent' }}
This is not good since it influence the over css state (try hover with and without this line and watch the difference) 
Any way, maybe we should put a comment that explains that, so no one will be confused again

2021-08-31 13:55 UTC, lustigy96 commented on src/common/OptionButton/OptionButton.styles.js
> +    backgroundColor: 'transparent',
doesn't make the job (look on hover)

2021-08-31 13:55 UTC, lustigy96 commented on src/pages/AddNodes/index.jsx
> +        tmpRow.data[2],
add a comment on each of those line to make it readable in future (which parameter in each index)

2021-08-31 14:07 UTC, carmeltsadok approved these changes

2021-09-05 10:19 UTC, lihi2910 commented on src/common/OptionButton/OptionButton.styles.js
> +    backgroundColor: 'transparent',
fix to transpert in hover

2021-09-05 10:20 UTC, lihi2910 commented on src/common/EditDeleteOptionsButton/EditDeleteOptionsButton.jsx
> +  allUnits,
? , its option button of edit and delete...

2021-09-05 10:21 UTC, lihi2910 commented on src/common/EditDeleteOptionsButton/EditDeleteOptionsButton.jsx
> +import React, { useState } from 'react';
we talked about this...

2021-09-05 11:12 UTC, lustigy96 commented on src/common/EditDeleteOptionsButton/EditDeleteOptionsButton.jsx
> +import { toast } from 'react-toastify';
you dont use it
```suggestion
```

2021-09-05 11:49 UTC, lustigy96 approved these changes

2021-09-05 12:12 UTC, merged