Feat/error messeges
alphayesodot/itur-client pull request #154
Opened 2021-09-05 12:29 UTC by lustigy96

2021-09-05 12:35 UTC, lustigy96 commented on src/pages/AddNodes/index.jsx
> +
```suggestion
```

2021-09-05 13:24 UTC, Delitefully requested changes

2021-09-05 13:24 UTC, Delitefully commented on src/i18n.js
> +            eventResult: 'עדכון תוצאות נכשל. נסה.י שוב מאוחר יותר',
any reason for using . instead of / in all of those translations?

2021-09-05 13:41 UTC, lustigy96 commented on src/i18n.js
> +            eventResult: 'עדכון תוצאות נכשל. נסה.י שוב מאוחר יותר',
Eliran chose that, but I think I will change

2021-09-05 14:22 UTC, Delitefully approved these changes

2021-09-05 19:38 UTC, lihi2910 commented on src/services/unit.service.js
> +  }, { maxAge: config.services.cachingTime });
are you add this variable? (in config services)

2021-09-05 19:38 UTC, lihi2910 commented on src/services/event.service.js
> +  static getEventById = mem(async (id) => {
maybe explaine what is mem in comment

2021-09-05 19:39 UTC, lihi2910 commented on src/i18n.js
> +         fail: {
in all this file, you need to ctrl shift f

2021-09-05 22:26 UTC, lustigy96 commented on src/services/unit.service.js
> +  }, { maxAge: config.services.cachingTime });
yes

2021-09-05 22:28 UTC, lustigy96 commented on src/services/event.service.js
> +  static getEventById = mem(async (id) => {
I added it in all project, it is commented in one of them (I think its wired to explain it in every file)
I think it should just be a way of work that everyone knows in our team 

Still add some, just in case

2021-09-05 22:32 UTC, lustigy96 commented on src/utils/errors.jsx
> +        return `errorKeys.${error.response?.data?.translationKey}`;
this is the default structure of http response, except the translationKey, which is obvious to be my key since it is in the data field of the http request

2021-09-06 11:49 UTC, lihi2910 approved these changes

2021-09-06 11:55 UTC, merged