Fix/node empty send
alphayesodot/itur-client pull request #158
Opened 2021-09-12 14:38 UTC by lihi2910

2021-09-14 13:42 UTC, carmeltsadok approved these changes

2021-09-19 09:31 UTC, carmeltsadok requested changes

2021-09-19 09:31 UTC, carmeltsadok commented on src/i18n.js
> +        allFields: 'יש למלא את כל השדות',
pull origin dev, there are changes in this file, especially in the error section.

2021-09-19 09:59 UTC, Delitefully approved these changes

2021-09-19 10:29 UTC, PCOffline approved these changes

2021-09-19 13:40 UTC, PCOffline approved these changes

2021-09-19 13:56 UTC, carmeltsadok approved these changes

2021-09-19 13:56 UTC, merged