Feat/header toolbars
alphayesodot/itur-client pull request #17
Opened 2021-04-28 12:01 UTC by lustigy96

2021-04-28 12:25 UTC, carmeltsadok requested changes

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.jsx
> +    if (hour >= morningHours.evning && hour < morningHours.night) {
```suggestion
    if (hour >= morningHours.evening && hour < morningHours.night) {
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.jsx
> +    const morningHours = { morning: 5, afternoon: 12, evening: 17, night: 21 };
```suggestion
    const hoursRange = { morning: 5, afternoon: 12, evening: 17, night: 21 };
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.jsx
> +      return t('headerBlessings.evning');
```suggestion
      return t('headerBlessings.evening');
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.jsx
> +            <img src='radar-logo.png' alt='' />
```suggestion
            <img src={logo} alt='' />
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.jsx
> +// import MenuIcon from '@material-ui/icons/Menu';
```suggestion
import logo from '../../utils/images/logo.svg';
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +// import luzIconActive from '../../utils/images/aside/aside-luz-button-active.svg';
```suggestion
import React from 'react';
import { Link } from 'react-router-dom';
import DashboardCard from '../DashboardCard/DashboardCard';
import useStyles from './SideBarNav.styles';
import settingsIcon from '../../utils/images/aside/settings.svg';
import interviewIcon from '../../utils/images/aside/aside-interview-button.svg';
import luzIcon from '../../utils/images/aside/aside-luz-button.svg';
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.styles.js
> +// import apptheme from '../../theme';
```suggestion
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/pages/XmlUpload/index.jsx
> +  // <div className={classes.root}>
```suggestion
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/pages/XmlUpload/index.jsx
> +  // </div>
```suggestion
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/pages/XmlUpload/index.styles.js
> +  // },
```suggestion
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/common/Header/Header.styles.js
> +    marginRight: '0.5rem',
```suggestion
    fontFamily: theme.typography.fontFamily,
    marginRight: '0.5rem',
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/pages/XmlUpload/index.jsx
> +    <DashboardCard className={classes.content}>
```suggestion
    <DashboardCard className={classes.root}>
```

2021-04-28 12:25 UTC, carmeltsadok commented on src/App.jsx
>  import useStyles from './App.styles';
There is a need to add to class `bodyContainer` in `App.styles.js` file the next fields: 
`paddingTop: '2rem',
 height: 'calc(100vh - 9rem)',`

2021-04-28 12:25 UTC, carmeltsadok commented on src/App.jsx
>  import useStyles from './App.styles';
And to the `Home` page's `index.styles.js` file in `root` the field `width: '100%'` so we can see the home page in its full width.

2021-04-29 06:55 UTC, carmeltsadok requested changes

2021-04-29 06:55 UTC, carmeltsadok commented on mockserver/config.js
> +  malshbSearch: '/search-malshab',
```suggestion
  malshabSearch: '/search-malshab',
```

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.styles.js
> +    // marginTop: '2rem',
```suggestion
```

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +  };
Move this to the declarations part.

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +        <Tooltip placement='top' title={t(`xmlPage.${iconDetails.tooltip}`)}>
```suggestion
        <Tooltip placement='top' title={t(`tooltip.${iconDetails.tooltip}`)}>
```

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +  const userRole = 'RAMAD_ITUR_OF_UNIT';
Get user's role from `userStore`'s `userProfile`.

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +    const src = iconDetails.urlPostfix === '/reports' ? iconDetails.imgActive : iconDetails.imgDef;
Why?

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +      <Link key={iconDetails.urlPostfix} className={classes.iconLink} to='/'>
```suggestion
      <Link key={iconDetails.urlPostfix} className={classes.iconLink} to={iconDetails.urlPostfix}>
```

2021-04-29 06:55 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +      <Link className={classes.iconLink} to='/'>
```suggestion
      <Link className={classes.iconLink} to='/settings'>
```

2021-04-29 11:04 UTC, lustigy96 commented on src/common/SideBarNav/SideBarNav.jsx
> +        <Tooltip placement='top' title={t(`xmlPage.${iconDetails.tooltip}`)}>
tooltip is not so good, so I changes it to sidebar (my mistake :D )

2021-04-29 11:12 UTC, lustigy96 commented on src/common/SideBarNav/SideBarNav.jsx
> +    const src = iconDetails.urlPostfix === '/reports' ? iconDetails.imgActive : iconDetails.imgDef;
just as example... suppose to get the url page.. but the pages are not done and I wanted to check and see the difference 
When some pages will be on dev, I will change :)

2021-04-29 11:16 UTC, lustigy96 commented on src/common/SideBarNav/SideBarNav.jsx
> +      <Link className={classes.iconLink} to='/'>
there is no page of settings... It is just an example.. 
When pages will be on dev I will synchronize with it..

2021-04-29 12:04 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +    const src = iconDetails.urlPostfix === '/reports' ? iconDetails.imgActive : iconDetails.imgDef;
We should also add to the switch in `app.jsx` the routes from the config. We can add an array of objects. Each object can be like that: `{ link: '', page: <></>}`

2021-04-29 13:57 UTC, carmeltsadok approved these changes

2021-04-29 13:57 UTC, merged