Bugfix/xml duplicate filename
alphayesodot/itur-client pull request #18
Opened 2021-04-28 15:33 UTC by PCOffline

2021-04-28 18:41 UTC, carmeltsadok commented
Change the pr so it will merge into dev :) @PCOffline

2021-04-29 06:08 UTC, PCOffline commented
> Change the pr so it will merge into dev :) @PCOffline

My mistake!

2021-04-29 06:20 UTC, carmeltsadok commented
Also, make sure you merge the most updated dev branch @PCOffline

2021-04-29 06:36 UTC, carmeltsadok requested changes

2021-04-29 06:36 UTC, carmeltsadok commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  function fixDuplicateFile(updatedFiles, file) {
Change to arrow function syntax according to es6.

2021-04-29 06:36 UTC, carmeltsadok commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +const COPY_SUFFIX = ' - Copy';
The duplicate named file is not necessarily a copy. So I think you should only add a number in brackets when there is a duplicate name.

2021-04-29 06:36 UTC, carmeltsadok commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +/* eslint-disable no-param-reassign */
Move it to the specific line

2021-04-29 06:36 UTC, carmeltsadok commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +      // eslint-disable-next-line no-cond-assign
Listen to this message :)

2021-04-29 07:34 UTC, lustigy96 requested changes

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +    for (const key in file) newFile[key] = file[key];
use deep copy with {...file} and not this for loop

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +    }
you should not handle the 'copy' instance, only numbers... so it is unnecessary

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  function fixDuplicateFile(updatedFiles, file) {
don't use the function syntax, use 
fixDuplicateFile = (updatedFiles, file) => {...}
instead

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  function fixDuplicateFile(updatedFiles, file) {
note: suppose you entered file(1), file(2), file (3), and then deleted file (2), the next filw you will drop will get the index '4', but suppose to be index '2' (instead of the deleted one)

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +      // eslint-disable-next-line no-cond-assign
If you can avoid the eslint remarks so do...

2021-04-29 07:34 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +        `^${fileName}${COPY_SUFFIX} \\([2-9]([0-9]+)?\\)\\${extension}$`,
you may start from '1' and not '2' (since its better to use numbers only and not the 'copy' first) and also, in case of (index =10) it's not working. (try to upload file 10 times and see).

2021-04-29 09:45 UTC, PCOffline commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +    for (const key in file) newFile[key] = file[key];
Doesn't work. Believe me, I tried every single way you could possibly think of. When I use object spread, it doesn't copy the __proto__ of file, by that omitting all the properties except for path (including name, size, type, etc.)

2021-04-29 10:59 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +    for (const key in file) newFile[key] = file[key];
I don,t think you should copy it anyway, just add it and override the relevant fields.. (talking to Yonatan)

2021-04-29 12:06 UTC, PCOffline commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +    for (const key in file) newFile[key] = file[key];
I can't.. 
`file.name = "..."` throws an error that it does not have a setter, only a getter. It's a read-only field.

2021-05-09 11:37 UTC, lustigy96 requested changes

2021-05-09 11:37 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +
This is not a good name since there is a real max-size. you may write conversion = 1000000
also, not capital letters.

2021-05-09 11:44 UTC, PCOffline commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +
Read-only values as such are usually written in MACRO_CASE. But sure, I'll change the name

2021-05-09 14:46 UTC, carmeltsadok approved these changes

2021-05-11 11:58 UTC, lustigy96 requested changes

2021-05-11 11:58 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  const fixDuplicateFile = (updatedFiles, file) => {
```suggestion
  const renameDuplicateFile = (updatedFiles, file) => {
```

This is a better name

2021-05-11 11:58 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +        updatedFiles = updatedFiles.concat(fixDuplicateFile(updatedFiles, file));
```suggestion
        updatedFiles = updatedFiles.concat(renameDuplicateFile(updatedFiles, file));
```

2021-05-11 11:58 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', // MIME type for .xlsx
maybe file type ?

2021-05-11 11:58 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  const CONVERSION = 1e6; // = 1,000,000
```suggestion
  const conversion= 1e6; // = 1,000,000
```

capital letters are for env variables only

2021-05-11 11:58 UTC, lustigy96 commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +          <p className={classes.limitation}>{t('xmlPage.sizeLimitation', { sizeLimit: configApp.xmlUpload.sizeLimit / CONVERSION })}</p>
```suggestion
          <p className={classes.limitation}>{t('xmlPage.sizeLimitation', { sizeLimit: configApp.xmlUpload.sizeLimit / conversion})}</p>
```

2021-05-11 14:23 UTC, PCOffline commented on src/pages/XmlUpload/components/DropZone/DropZone.jsx
> +  const CONVERSION = 1e6; // = 1,000,000
As I said, MACRO_CASE (also known as CONSTANT_CASE) is used when a variable is constant and is used solely to replace a magic value. It is a global convention. If you insist on it, I'll change it

2021-05-13 11:57 UTC, PCOffline commented
All done

2021-05-13 11:59 UTC, lustigy96 approved these changes

2021-05-13 12:00 UTC, merged