Feat/track page
alphayesodot/itur-client pull request #20
Opened 2021-05-03 10:29 UTC by carmeltsadok

2021-05-04 12:58 UTC, lustigy96 requested changes

2021-05-04 12:58 UTC, lustigy96 commented on src/pages/Track/components/NodeGroupSelect/NodeGroupSelect.jsx
> +import React, { useEffect, useState } from 'react';
Write general remarks: 
1. The padding width is not equal
2. I think that during selection only one node group should be background-colored on hover. All the others should be white. (If this is the default by material-UI so live it as it is)
3. I think you should add an empty line. choosing it will cause the option "choose node group"

2021-05-04 12:58 UTC, lustigy96 commented on src/pages/Track/components/ScheduleCard/ScheduleCard.jsx
> +        <Avatar alt='avatar' src={avatar} className={classes.avatar} />
```suggestion
        <Avatar alt='icon' src={avatar} className={classes.avatar} />
```

2021-05-04 12:58 UTC, lustigy96 commented on src/pages/Track/components/ScheduleCard/ScheduleCard.jsx
> +        </Typography>
add padding-width on this card

2021-05-04 12:58 UTC, lustigy96 commented on .eslintrc.json
> +    "import/no-unresolved": 0,
Some of these rules are important so I don't think they should be in this file. Let's work through this together.

2021-05-04 12:58 UTC, lustigy96 commented on src/App.jsx
>  import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
I write it here... but, there is a file in "public/favision.ico" (This is our logo icon). Don't we have a better one? This one is pixeled.

2021-05-05 06:54 UTC, carmeltsadok commented on src/pages/Track/components/InterviewsList/InterviewsList.jsx
> +const timeDifference = 1800000; // 30 minutes
I was told that each interview will be 30 minutes long.

2021-05-05 07:03 UTC, carmeltsadok commented on src/pages/Track/components/Header/Header.jsx
> +            type='date'
I can't put the same class on both `NodeGroupSelect` and `TextField` because they don't share the same styles file.
I added more padding now to `TextField`.

2021-05-05 07:12 UTC, carmeltsadok commented on src/pages/Track/components/InterviewItem/InterviewItem.styles.js
> +
Didn't get you :) Let's sit together

2021-05-05 10:31 UTC, carmeltsadok commented on src/pages/Track/components/InterviewsList/InterviewsList.jsx
> +        return interview.results ? 'DONE' : 'CANCELED';
Why would they?

2021-05-05 10:31 UTC, carmeltsadok commented on src/pages/Track/components/InterviewsList/InterviewsList.jsx
> +        );
They told me that I would show 30 min long (it is just for the ramad)

2021-05-09 07:56 UTC, carmeltsadok commented on src/pages/Track/components/NodeGroupSelect/NodeGroupSelect.jsx
> +import React, { useEffect, useState } from 'react';
- Results from the bottom

2021-05-09 14:40 UTC, carmeltsadok commented on .eslintrc.json
> +    "import/no-unresolved": 0,
`no-underscore-dangle` is for `_id`

2021-05-09 14:40 UTC, carmeltsadok commented on src/pages/Track/components/NodeGroupSelect/NodeGroupSelect.jsx
> +import React, { useEffect, useState } from 'react';
1. fixed
2. It is default by material ui

2021-05-10 08:41 UTC, lustigy96 approved these changes

2021-05-23 12:10 UTC, maykremer requested changes

2021-05-24 06:51 UTC, maykremer approved these changes

2021-05-24 08:09 UTC, merged