User managing
alphayesodot/itur-client pull request #25
Opened 2021-05-24 13:03 UTC by maykremer

2021-05-24 14:08 UTC, carmeltsadok requested changes

2021-05-25 07:25 UTC, carmeltsadok requested changes

2021-05-25 07:25 UTC, carmeltsadok commented on src/common/InterviewerHeader/InterviewerHeader.jsx
> +import React from 'react';
Remove file and folder. not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/i18n.js
> +      },
Remove. not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/i18n.js
> +      },
Separate to better claseses

2021-05-25 07:25 UTC, carmeltsadok commented on src/stores/Units.store.js
> +import { makeAutoObservable } from 'mobx';
I think this file not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/services/user.service.js
> +  }
This api route is incorrect. The `unitId` should be in the params, this is get user by id

2021-05-25 07:25 UTC, carmeltsadok commented on src/services/unit.service.js
> +    const res = await axios.get(`${await config.uri.api}/api/unit`).catch(() => {});
remove catch. The catch will be when calling the function.

2021-05-25 07:25 UTC, carmeltsadok commented on src/services/unit.service.js
> +    const res = await axios.post(`${await config.uri.api}/api/unit`, { unitName }).catch(() => {});
remove catch. The catch will be when calling the function.

2021-05-25 07:25 UTC, carmeltsadok commented on src/services/user.service.js
> +  }
remove catch. The catch will be when calling the function.

2021-05-25 07:25 UTC, carmeltsadok commented on src/services/user.service.js
> +    const res = await axios.post(`${await config.uri.api}/api/user/`, { unitId, role, userName }).catch(() => {});
remove catch. The catch will be when calling the function.

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/index.jsx
> +    <div className={classes.mainDiv}>
This should be root

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/index.jsx
> +        className={classes.addUnitDialog}
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/index.styles.js
> +  },
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/Units/Units.jsx
> +    <DashboardCard className={classes.units}>
Should be root

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsUsersTable/UnitDetailsUsersTable.styles.js
> +  },
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsUsersTable/UnitDetailsUsersTable.styles.js
> +
Not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsTableRow/UnitDetailsTableRow.jsx
> +    <TableRow key={roleToDisplay} className={classes.tableRow}>
Should be root

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsTableRow/UnitDetailsTableRow.styles.js
> +  },
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsTableRow/UnitDetailsTableRow.styles.js
> +  },
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsTableRow/UnitDetailsTableRow.styles.js
> +  },
not in use

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> +            alt=''
```suggestion
            alt='user logo'
```

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> +            alt=''
```suggestion
            alt='home logo'
```

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> +            width='23rem'
add to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> +            width='36rem'
add to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetails/UnitDetails.jsx
> +    <div>
no need for this div

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetails/UnitDetails.jsx
> +      <DashboardCard className={classes.unitDetails}>
should be root

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/UnitDetails/UnitDetails.jsx
> +              <div className={classes.root}>
not such class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/SearchBar/SearchBar.jsx
> +            className={classes.searchLogo}
not such class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/SearchBar/SearchBar.jsx
> +            width='15rem'
add to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/SearchBar/SearchBar.jsx
> +            alt=''
```suggestion
            alt='search logo'
```

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/SearchBar/SearchBar.jsx
> +/* eslint-disable no-unused-expressions */
check if needed. If so, tell me and we will see if needed to add to eslint file

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/RoleUsersDialog/RoleUsersDialog.jsx
> +              <strong style={{ marginRight: '-1rem' }} className={classes.titles}>{t('text.amount')}</strong>
add `style={{ marginRight: '-1rem' }}` to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/RoleUsersDialog/RoleUsersDialog.jsx
> +            <Typography style={{ wordSpacing: '1rem' }}>
add `style={{ wordSpacing: '1rem' }}` to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/NewUsersTable/NewUsersTable.jsx
> +              <TableCell align='center'>DFGJKL123456</TableCell>
what is it `DFGJKL123456` ?

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/NewUsersDialog/NewUsersDialog.jsx
> +              <Typography style={{ fontSize: '1.1rem' }}>
add styles to classes

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/NewUsersDialog/NewUsersDialog.jsx
> +              <strong style={{ marginRight: '-1rem' }} className={classes.titles}>{t('text.amount')}</strong>
add style to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/NewUsersDialog/NewUsersDialog.jsx
> +            <Typography style={{ wordSpacing: '1rem' }}>
add style to class

2021-05-25 07:25 UTC, carmeltsadok commented on src/pages/UserManaging/NewUsersDialog/NewUsersDialog.jsx
> +      usernamesList.push('DFGJKL123456');
what is it `DFGJKL123456` ?

2021-05-25 13:10 UTC, carmeltsadok requested changes

2021-05-25 13:10 UTC, carmeltsadok commented on src/pages/UserManagement/RoleUsersDialog/RoleUsersDialog.styles.js
> +  },
not in use

2021-05-25 14:53 UTC, carmeltsadok commented
Move all components to `components` folder @maykremer

2021-05-27 11:52 UTC, carmeltsadok requested changes

2021-05-27 11:52 UTC, carmeltsadok commented on src/i18n.js
> +      userManagement: {
Remove `userManagement` field. Add the other fields into the other existing fields

2021-05-27 11:52 UTC, carmeltsadok commented on src/pages/UserManagement/components/NewUsersTable/NewUsersTable.jsx
> +      <Table aria-label='simple table' dir='rtl'>
Is `dir='rtl'` required?

2021-05-27 11:52 UTC, carmeltsadok commented on src/pages/UserManagement/components/NewUsersTable/NewUsersTable.styles.js
> +    direction: 'rtl',
is required?

2021-05-27 11:52 UTC, carmeltsadok commented on src/pages/UserManagement/components/RolesDialogsHeadLine/RolesDialogsHeadLine.jsx
> +        </Typography>
You can do it in one `Typography`

2021-05-27 12:07 UTC, carmeltsadok requested changes

2021-05-27 12:07 UTC, carmeltsadok commented on src/i18n.js
> +        ramadIturAssistant: 'עוזר רמ"ד איתור',
```suggestion
        ramadIturAssistant: 'עוזר.ת רמ"ד איתור',
```

2021-05-30 11:09 UTC, carmeltsadok approved these changes

2021-05-30 11:35 UTC, AdarPascal approved these changes

2021-05-30 11:35 UTC, merged