Feat/luz page
alphayesodot/itur-client pull request #26
Opened 2021-06-02 15:57 UTC by carmeltsadok

2021-06-07 06:15 UTC, lustigy96 requested changes

2021-06-07 06:15 UTC, lustigy96 commented on src/pages/Luz/index.styles.js
> +  },
What is that? we always use it and I don't know

2021-06-07 06:15 UTC, lustigy96 commented on src/pages/Track/components/InterviewItem/InterviewItem.jsx
> +  const { status, malshabShort, time } = event;
Isn't it better to take it all as a properties?

2021-06-07 06:34 UTC, carmeltsadok commented on mockserver/nodeGroup/nodeGroup.manager.js
> +      res.send(nodeGroups[0]);
because in the api when the role is an `INTERVIEWER` it returns only one nodeGroup

2021-06-07 06:35 UTC, carmeltsadok commented on mockserver/userdata.js
> +    userID: '507f1f77bcf86cd799439021',
Because it shows the events depends on the inteviewer's id

2021-06-07 06:37 UTC, carmeltsadok commented on src/App.styles.js
> -      height: 'calc(100vh - 3rem)',
Its useless and fucked other things

2021-06-07 06:37 UTC, carmeltsadok commented on src/common/InterviewStatusIcon/InterviewStatusIcon.jsx
> +  };
How?

2021-06-07 06:37 UTC, carmeltsadok commented on src/common/InterviewsList/InterviewsList.jsx
>        case 'FUTURE':
How?

2021-06-07 06:39 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
>    };
The div is necessary to center the icon and the title. And I don't think that clicking on the title is right for navigation.

2021-06-07 06:41 UTC, carmeltsadok commented on src/pages/Luz/index.styles.js
> +  },
You can see why when it is not written. When the screen is small, I want to have a smaller screen because of the navbar

2021-06-07 06:51 UTC, carmeltsadok commented on src/pages/Track/components/InterviewItem/InterviewItem.jsx
> +  const { status, malshabShort, time } = event;
This component is generally so one `InterviewItem` component is using other `event`'s properties than another `InterviewItem` component.

2021-06-08 08:13 UTC, lustigy96 requested changes

2021-06-08 12:35 UTC, lustigy96 approved these changes

2021-06-08 12:37 UTC, maykremer approved these changes

2021-06-08 12:58 UTC, merged