Feat/reports
alphayesodot/itur-client pull request #33
Opened 2021-06-16 20:30 UTC by carmeltsadok

2021-06-20 13:43 UTC, lustigy96 requested changes

2021-06-20 13:43 UTC, lustigy96 commented on src/pages/Reports/components/InputsRow/InputsRow.jsx
> +            <RedoIcon />
Maybe another arraow is better to the revert operation (more round)

2021-06-20 13:43 UTC, lustigy96 commented on src/common/GenericSelect/GenericSelect.jsx
> +import React, { useState, useEffect } from 'react';
choosing the second value - the menu goes up 
I fix that in my code, you can look and add it in yours

2021-06-20 13:43 UTC, lustigy96 commented on src/common/NodeGroupSelect/NodeGroupSelect.jsx
>  import React, { useEffect, useState } from 'react';
choosing the second value - the menu goes up
I fix that in my code, you can look and add it in yours

2021-06-20 13:43 UTC, lustigy96 commented on src/pages/Reports/components/InputsRow/InputsRow.jsx
> +import React, { useEffect, useState } from 'react';
after the creation - delete all data in input fields

2021-06-20 13:43 UTC, lustigy96 commented on src/pages/Reports/components/Spreadsheet/Spreadsheet.jsx
> +import React, { useState, useEffect } from 'react';
use margins right + left

2021-06-20 13:43 UTC, lustigy96 commented on src/pages/Reports/index.jsx
> +          </CSVLink>
add padding (I wrote this already, but I just to clarify the place)

2021-06-20 13:43 UTC, lustigy96 commented on src/pages/Reports/components/Spreadsheet/Spreadsheet.styles.js
> +    overflowY: 'auto',
overflowX is needed too

2021-06-20 14:58 UTC, carmeltsadok commented on src/i18n.js
> -        noNodeGroups: 'אין מסלולים',
It was for my track page and I changed it. Maybe on your pr you need to add it but it is not in dev

2021-06-20 15:10 UTC, carmeltsadok commented on src/index.jsx
>    document.getElementById('root'),
I removed the react strict mode because it bothered me :)

2021-06-20 15:50 UTC, carmeltsadok commented on src/pages/Reports/components/InputsRow/InputsRow.jsx
> +            <RedoIcon />
1. I don't think it is needed. It is quite obvious when it is disabled.
2. love you
3. fixed
4. fixed

2021-06-21 13:03 UTC, lustigy96 approved these changes

2021-06-22 13:17 UTC, maykremer approved these changes

2021-06-22 13:18 UTC, merged