Feat/node group page
alphayesodot/itur-client pull request #34
Opened 2021-06-20 14:41 UTC by lustigy96

2021-06-21 09:00 UTC, carmeltsadok requested changes

2021-06-21 09:00 UTC, carmeltsadok commented on src/pages/NodeGroupPage/index.jsx
> +      <DashboardCard className={classes.dashbord}>
1. Change to `classes.dashboard`
2. Fix dashboard height when not on 100%

2021-06-21 09:00 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/Header/Header.jsx
> +              className={classes.input}
Remove underline of input when focus and on hover

2021-06-21 09:00 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/NodeGroupDialog/NodeGroupDialog.jsx
> +          <SelectCheckboxItem
I think that we should use the generic component. because I already implemented that when selecting items they are written in the select. I can do it with you.. I promise it is 2 seconds :)))))

2021-06-21 09:00 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/NodeGroupDialog/NodeGroupDialog.jsx
> +          className={classes.saveButton}
I would do an inner border when hovering the button (because the width of the border moves the other inputs up)

2021-06-21 09:00 UTC, carmeltsadok commented on src/common/DataTable/DataTable.jsx
> +    <TableContainer className={classes.root}>
stretch the table to 100%

2021-06-21 11:19 UTC, carmeltsadok requested changes

2021-06-21 11:19 UTC, carmeltsadok commented on mockserver/userdata.js
> +    userId: '507f1f77bcf86cd799439021',
it was `userId` because this is how it is requested in the server

2021-06-21 11:19 UTC, carmeltsadok commented on src/common/DataTable/DataTable.jsx
> +const DataTable = ({ rowsData, colomnsNames }) => {
change to `columnNames`

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/Luz/index.jsx
> +        currentUser.userId,
this is how it will be getting from the server (`userID`)

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/Header/Header.jsx
> +const filterSearch = (prefix: string, allNodeGroupRows: Array, setNodeGroupRowsToShow) => {
how does it work with types when it is js?

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/NodeGroupDialog/NodeGroupDialog.jsx
> +        case 'PROFETIONAL_RAMAD':
we should add a role enum like in the mockserver for all the app

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/OptionsButton/OptionsButton.jsx
> +            <img className={classes.img} width='15rem' src={deleteImg} alt='see more' />
add width to class

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/OptionsButton/OptionsButton.jsx
> +            <img className={classes.img} width='17rem' src={editImg} alt='see more' />
add to width class

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +  const menuItemHieght = 48;
change to `menuItemHeight `

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +      },
add to class

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.styles.js
> +  },
```suggestion
```

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +              classes={{ root: classes.checkbox, checked: classes.checkedCheckbox }}
```suggestion
              classes={{ root: classes.checkbox }}
```

2021-06-21 11:19 UTC, carmeltsadok commented on src/pages/NodeGroupPage/index.styles.js
> +    height: '73.5vh',
this is probably the problem

2021-06-21 11:19 UTC, carmeltsadok commented on src/services/user.service.js
> +export const Role = {
now I see that there is a role enum, so there is a need to change all the dev part to use it

2021-06-21 11:19 UTC, carmeltsadok commented on src/services/user.service.js
> +// export default UserService;
```suggestion
```

2021-06-21 11:19 UTC, carmeltsadok commented on src/theme.js
> +    dilogs: {
change to `dialogs`

2021-06-21 14:21 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/NodeGroupDialog/NodeGroupDialog.jsx
> +          <SelectCheckboxItem
I think that we put it on issue and continue since it takes a lot of time. I don't think it is going to be so fast

2021-06-21 14:23 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/NodeGroupDialog/NodeGroupDialog.jsx
> +          <SelectCheckboxItem
🤓🤓🤓👍🏼👍🏼👍🏼

2021-06-21 14:29 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/OptionsButton/OptionsButton.jsx
> +        style={{ backgroundColor: 'transparent' }}
hahha not working, this is a special bug\feature

2021-06-21 14:30 UTC, lustigy96 commented on src/pages/NodeGroupPage/index.jsx
> +  const colNames = [t('tableColumns.nodeGroupName'), t('tableColumns.unit'), t('tableColumns.users'), t('tableColumns.ramadOfUnit')];
unneeded talking to yuval

2021-06-21 14:32 UTC, lustigy96 commented on src/common/DataTable/DataTable.jsx
> +          ))}
yes you are right.. I planned to do this in another PR (questionnaire PR) 
since I noticed this bug only later... so I will add it next

2021-06-21 14:32 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +              classes={{ root: classes.checkbox, checked: classes.checkedCheckbox }}
not true, won't work

2021-06-21 14:35 UTC, lustigy96 commented on src/services/user.service.js
> +export const Role = {
enum is in mock server, and user service is not... 
i can insert this role to other components...

2021-06-22 14:09 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/OptionsButton/OptionsButton.jsx
> +            <img className={classes.img} width='15rem' src={deleteImg} alt='see more' />
talked about that

2021-06-22 14:09 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/OptionsButton/OptionsButton.jsx
> +            <img className={classes.img} width='17rem' src={editImg} alt='see more' />
talked about that

2021-06-22 14:11 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.jsx
> +      },
wont work
it includes a const calculation

2021-06-22 14:11 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/SelectCheckboxItem/SelectCheckboxItem.styles.js
> +  },
needed

2021-06-22 14:26 UTC, carmeltsadok approved these changes

2021-06-22 14:26 UTC, carmeltsadok commented on src/common/DataTable/DataTable.jsx
> + * @param {*} iconColomnsImages: array of icons that should be in an a non-named columns.
```suggestion
```

2021-06-24 07:39 UTC, merged