feature/preparation-kit
alphayesodot/itur-client pull request #43
Opened 2021-07-06 14:49 UTC by PCOffline

Add Preparation Kit Page

2021-07-06 21:31 UTC, carmeltsadok requested changes

2021-07-06 21:31 UTC, carmeltsadok commented on package.json
>    "private": true,
Writing it here, but make sure you fix all conflicts before opening a pr :)

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +import interviewerVideo from './pdf/video.mp4';
not exist, app not running because it can't resolve it

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +    <div className={classes.root}>
wrap this component with `DashboardCard` to be matched with all pages's styling

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +        </div>
make it a bit prettier using material-ui components

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +      </div>
couldn't see it because of the import :)

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +            Previous
Change to hebrew

2021-07-06 21:31 UTC, carmeltsadok commented on src/common/SideBarNav/SideBarNav.jsx
> +const Sidebar = React.forwardRef((props, ref) => {
Why did you add ref?

2021-07-06 21:31 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +      <div className={classes.PDFContainer}>
also, make the page the same height as the sidebar so there will be no scrolling

2021-07-08 12:14 UTC, PCOffline commented on src/pages/PreparationKit/index.jsx
> +    <div className={classes.root}>
Done

2021-07-08 12:14 UTC, PCOffline commented on src/pages/PreparationKit/index.jsx
> +        </div>
Done

2021-07-08 12:14 UTC, PCOffline commented on src/pages/PreparationKit/index.jsx
> +            Previous
Done

2021-07-08 12:14 UTC, PCOffline commented on src/common/SideBarNav/SideBarNav.jsx
> +const Sidebar = React.forwardRef((props, ref) => {
Fixed

2021-07-08 12:50 UTC, PCOffline commented on package.json
>    "private": true,
Done

2021-07-11 18:14 UTC, carmeltsadok requested changes

2021-07-11 18:14 UTC, carmeltsadok commented on mockserver/preparation-kit/preparation-kit.manager.js
> +import { dirname } from 'path';
rename file to `preparationKit.manager.js`

2021-07-11 18:14 UTC, carmeltsadok commented on mockserver/preparation-kit/preparation-kit.router.js
> +import express from 'express';
rename file to `preparationKit.router.js`

2021-07-11 18:14 UTC, carmeltsadok commented on src/pages/PreparationKit/index.jsx
> +          noData={<p>No File Chosen</p>}
maybe change ti hebrew

2021-07-11 18:18 UTC, carmeltsadok requested changes

2021-07-11 18:18 UTC, carmeltsadok commented on mockserver/preparation-kit/preparation-kit.manager.js
> +import { dirname } from 'path';
Change folder's namer to `preparationKit`

2021-07-11 18:19 UTC, carmeltsadok requested changes

2021-07-11 18:19 UTC, carmeltsadok commented on mockserver/preparation-kit/preparation-kit.manager.js
> +  }
add files to git

2021-07-11 18:24 UTC, carmeltsadok commented on mockserver/preparation-kit/preparation-kit.manager.js
> +  }
about the pdf- make a mock like the video you sent me so it won't be free on the internet :)

2021-07-11 18:30 UTC, carmeltsadok requested changes

2021-07-11 18:30 UTC, carmeltsadok commented on src/pages/PreparationKit/index.styles.js
> +    display: 'flex',
add `alignItems: 'center',`

2021-07-11 18:30 UTC, carmeltsadok commented on src/pages/PreparationKit/index.styles.js
> +      alignItems: 'stretch',
```suggestion
```

2021-07-11 18:30 UTC, carmeltsadok commented on src/pages/PreparationKit/index.styles.js
> +    marginLeft: '10%',
```suggestion
    marginLeft: '10%',
    [theme.breakpoints.down('sm')]: {
      marginLeft: '0',
    },
```

2021-07-11 18:30 UTC, carmeltsadok commented on src/pages/PreparationKit/index.styles.js
> +    },
```suggestion
```

2021-07-11 18:30 UTC, carmeltsadok commented on src/pages/PreparationKit/index.styles.js
> +      alignItems: 'stretch',
Suggesting another styling in this file: centering the documents on small screen

2021-07-12 09:28 UTC, PCOffline commented on mockserver/preparation-kit/preparation-kit.manager.js
> +import { dirname } from 'path';
done

2021-07-12 09:28 UTC, PCOffline commented on mockserver/preparation-kit/preparation-kit.router.js
> +import express from 'express';
done

2021-07-12 09:28 UTC, PCOffline commented on src/pages/PreparationKit/index.jsx
> +          noData={<p>No File Chosen</p>}
done

2021-07-12 09:29 UTC, PCOffline commented on mockserver/preparation-kit/preparation-kit.manager.js
> +  }
done

2021-07-12 09:33 UTC, PCOffline commented on src/pages/PreparationKit/index.styles.js
> +    display: 'flex',
This breaks the arrows placement

2021-07-12 09:36 UTC, PCOffline commented on src/pages/PreparationKit/index.styles.js
> +      alignItems: 'stretch',
Adding `alignItems: center` breaks the placement and makes the document go outside of the screen

2021-07-12 16:50 UTC, carmeltsadok approved these changes

2021-07-14 14:49 UTC, lustigy96 commented
Why did you add such a big file to the mock server? it that neccesery? It explodes the client repo @carmeltsadok @maykremer @PCOffline

2021-07-15 12:32 UTC, merged