Feat/questionnaire page
alphayesodot/itur-client pull request #44
Opened 2021-07-07 13:53 UTC by lustigy96

2021-07-07 14:03 UTC, Delitefully commented on src/i18n.js
> +        malshabAppreciateor: 'מעריך ומשל"ב',
appreciator instead of appreciateor

2021-07-07 14:11 UTC, Delitefully requested changes

2021-07-07 14:11 UTC, Delitefully commented on src/i18n.js
> +        appreciateor: 'מעריך',
same as above

2021-07-07 14:11 UTC, Delitefully commented on src/i18n.js
> +        multiple: 'אמריקאי',
This should be swapped with the option below, multi-select allows multiple values and checkbox only allows a single value

2021-07-07 14:11 UTC, Delitefully commented on src/pages/QuestionnaireSchemaPage/index.jsx
> +   * import all questionnaires - at the beeging only
beginning

2021-07-07 14:11 UTC, Delitefully commented on src/common/OpetionButton/OpetionButton.jsx
> +import useStyles from './OpetionButton.styles';
typo in the component name, option instead of opetion

2021-07-07 14:11 UTC, Delitefully commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireDialog/QuestionnaireDialog.jsx
> +      // return state to be unchanges
unchanged

2021-07-07 14:11 UTC, Delitefully commented on src/pages/QuestionnaireSchemaPage/components/Question/Question.jsx
> +  // set requried fields
required

2021-07-07 18:58 UTC, carmeltsadok requested changes

2021-07-07 18:58 UTC, carmeltsadok commented on src/appConf.js
> +  unitCreation: '/unit-creation',
I think `unitCreation` should be removed

2021-07-07 18:58 UTC, carmeltsadok commented on src/common/GenericSelect/GenericSelect.styles.js
> +    // padding: '1em',
fix

2021-07-07 18:58 UTC, carmeltsadok commented on src/common/OpetionButton/OpetionButton.jsx
> +import useStyles from './OpetionButton.styles';
yes it is a typo :) the folders as well

2021-07-07 18:58 UTC, carmeltsadok commented on src/i18n.js
> +        malshabAppreciateor: 'מעריך ומשל"ב',
change to 'מלש"ב'

2021-07-07 18:58 UTC, carmeltsadok commented on mockserver/user/db.js
> +    unitId: '507f191e810c19729de861ea',
```suggestion
```

2021-07-07 18:58 UTC, carmeltsadok commented on mockserver/user/enum.js
> +  malshab: 'MALSHAB',
change to `Malshab`

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/NodeGroupPage/components/NodeGroupOptionsButton/NodeGroupOptionsButton.jsx
> +      });
add catch with toast on error

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/Header/Header.jsx
> +                if (e.charCode === 13) {
use const for enter code

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/MultipleChoice/MultipleChoice.jsx
> +                  <ClearIcon size='s' className={classes.deleteIcon} />
is `size='s'` working?

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/Question/Question.jsx
> +  const quesitonTypes = [
change to `questionTypes`

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/Question/Question.jsx
> +    if (questionType && !currentQuestion && questionType.id !== '0') {
add  const for the choose option's id ('0')

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireDialog/QuestionnaireDialog.jsx
> +              <div className={classes.noNodeGroups}>
change class name to `noNodes`

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireDialog/QuestionnaireDialog.styles.js
> +    flexDirection: 'row',
```suggestion
```

2021-07-07 18:58 UTC, carmeltsadok commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireOptionsButton/QuestionnaireOptionsButton.jsx
> +      });
add catch with toast on error

2021-07-07 18:58 UTC, carmeltsadok commented on src/services/QuestionnaireSchema.service.js
> +export class QuestionnaireSchemaService {
change to `export default`

2021-07-07 18:58 UTC, carmeltsadok commented on src/services/auth.service.js
> +    window.location.replace('http://localhost:8080/login/4');
fix

2021-07-07 18:58 UTC, carmeltsadok commented on src/services/config.service.js
> +    // const { data } = await axios.get('/config', { ...headers });
fix

2021-07-07 18:59 UTC, carmeltsadok requested changes

2021-07-07 18:59 UTC, carmeltsadok commented on src/services/QuestionnaireSchema.service.js
> +import axios from 'axios';
change file name to `questionnaireSchema.service.js` (low-case q)

2021-07-08 10:16 UTC, lustigy96 commented on src/appConf.js
> +  unitCreation: '/unit-creation',
it is here since you pushed it on the App.jsx and it makes bugs

2021-07-08 10:20 UTC, lustigy96 commented on src/common/GenericSelect/GenericSelect.styles.js
> +    // padding: '1em',
check together the impact on your stuff

2021-07-08 12:11 UTC, carmeltsadok approved these changes

2021-07-08 12:44 UTC, Delitefully approved these changes

2021-07-08 12:44 UTC, Delitefully commented on src/common/GenericSelect/GenericSelect.jsx
> + * @param {*} setSelectedValue: set state function of the slected value.
```suggestion
 * @param {*} setSelectedValue: set state function of the selected value.
```

2021-07-08 12:48 UTC, merged