Roles select on development
alphayesodot/itur-client pull request #63
Opened 2021-07-13 18:34 UTC by carmeltsadok

2021-07-14 14:45 UTC, lustigy96 requested changes

2021-07-14 14:45 UTC, lustigy96 commented on src/pages/QuestionnaireSchemaPage/components/Header/Header.styles.js
> +    maxHeight: '5rem',
```suggestion
height: '5rem'
```

2021-07-14 14:45 UTC, lustigy96 commented on src/pages/NodeGroupPage/components/Header/Header.styles.js
> +    maxHeight: '5rem',
```suggestion
    height: '5rem',
```

2021-07-14 14:45 UTC, lustigy96 commented on src/common/Header/Header.styles.js
> +    padding: '0.2rem 0',
on reports page - add margin-bottom in sub-header (just so it, although it is not here in the changed files) 
also, this header select is ugly (haha) \\ just for the next time 
make it like the select in the reports page. maybe add a common css configuration

2021-07-14 14:45 UTC, lustigy96 commented on src/common/Header/Header.jsx
> +
only in development state

2021-07-14 15:13 UTC, maykremer approved these changes

2021-07-14 15:32 UTC, PCOffline requested changes
Instead of using `const` and then immediately returning it, put the expression inside the

2021-07-15 08:17 UTC, lustigy96 approved these changes

2021-07-15 08:17 UTC, merged