feature/events-calendar
alphayesodot/itur-client pull request #75
Opened 2021-07-19 16:58 UTC by PCOffline

2021-07-19 16:59 UTC, PCOffline commented
I am not sure about the styling of the Show All button

2021-07-19 17:47 UTC, carmeltsadok requested changes

2021-07-19 17:47 UTC, carmeltsadok commented on src/pages/MalshabSearch/components/EventsSection/EventsSection.jsx
> +            onChange={() => setShowAll((oldShowAll) => !oldShowAll)}
here, set the events to all events

2021-07-19 17:47 UTC, carmeltsadok commented on src/pages/MalshabSearch/components/EventsSection/EventsSection.jsx
> +    if (showAll) setShowedEvents(events);
`showAll` state is redundent. When clicking on a date after clicking on the showAll button, we still see all of the events.

2021-07-19 17:47 UTC, carmeltsadok commented on src/pages/MalshabSearch/components/EventsSection/EventsSection.styles.js
> +  showAllButton: {
make the button orange and rounder

2021-07-19 17:47 UTC, carmeltsadok commented on src/pages/MalshabSearch/components/EventsSection/EventsSection.styles.js
> +  showAllButton: {
the selected part is useless (because we do want to be able to select a date from the calendar, and to make it change the events list)

2021-07-19 17:49 UTC, carmeltsadok requested changes

2021-07-19 17:49 UTC, carmeltsadok commented on src/pages/MalshabSearch/components/EventsSection/EventsSection.jsx
> +  (first, second) => new Date(second.time).getTime() - new Date(first.time).getTime(),
```suggestion
  (first, second) => new Date(first.time).getTime() - new Date(second.time).getTime(),
```

2021-07-20 08:52 UTC, carmeltsadok approved these changes

2021-07-20 08:53 UTC, merged