Interviewer dashboard
alphayesodot/itur-client pull request #79
Opened 2021-07-20 10:57 UTC by AdarPascal

2021-07-20 14:24 UTC, carmeltsadok requested changes

2021-07-20 15:53 UTC, carmeltsadok requested changes

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/CheckboxAnswer/CheckboxAnswer.jsx
> +              style={{ color: '#02aecd' }}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/CheckboxAnswer/CheckboxAnswer.jsx
> +          label={<span style={{ fontSize: '1rem' }}>{option}</span>}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/CheckboxAnswer/CheckboxAnswer.jsx
> +              style={{ color: '#02aecd' }}
same

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.jsx
> +              style={{ paddingRight: '0' }}
same.

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.jsx
> +        <DialogTitle style={{ padding: '24px 24px 0px 24px' }}>
same

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.styles.js
> +    maxWidth: '160px',
change to rem/em

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.styles.js
> +    minHeight: '36px',
change to rem/em

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.styles.js
> +    '& > input': { textAlign: 'right', width: '60px' },
change to width rem/em

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/Question.styles.js
> +    '& > div > button': { color: '#02aecd' },
get color from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/ScaleAnswer/ScaleAnswer.jsx
> +                style={{ color: '#02aecd' }}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/ScaleAnswer/ScaleAnswer.styles.jsx
> +    marginRight: '5px',
change to em/rem

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/TextAnswer/TextAnswer.styles.jsx
> +      borderBottom: '2px solid #02aecd',
get color from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Questionnaire.jsx
> +          style={{ color: '#fff', height: '22.8rem' }}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Questionnaire.styles.js
> +      backgroundColor: '#cc9432',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Highlights/Highlights.jsx
> +        <span style={{ color: '#FCB333', fontWeight: 500, minWeight: '6rem', fontSize: '1.2rem' }}>נקודות ודגשים</span>
get from i18n

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Highlights/Highlights.styles.js
> +    backgroundColor: '#0f2231',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/Malshab.jsx
> +      <div style={{ display: 'flex', justifyContent: 'center', height: '25rem' }}>
same

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/Malshab.styles.js
> +  },
usless class

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/Malshab.styles.js
> +      color: '#EDF4F5',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/Malshab.styles.js
> +    backgroundColor: '#E51515',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.jsx
> +const enumTogender = (e) => (e === 1 ? 'זכר' : 'נקבה');
get from i18n

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.jsx
> +    return malshab[parameterName].length > 0 ? (
```suggestion
    return malshab[parameterName].length ? (
```

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.styles.js
> +    backgroundColor: '#f3f5f7',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.styles.js
> +    color: '#00afcc',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.styles.js
> +    fill: '#9aa3aa',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.styles.js
> +    // paddingRight: '50px',
```suggestion
```

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabDetails/MalshabDetails.styles.js
> +    paddingBottom: '13px',
change to rem/em

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabToolbar/MalshabToolbar.jsx
> +          // disabled
```suggestion
```

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabToolbar/MalshabToolbar.styles.js
> +    backgroundColor: '#E51515',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabToolbar/MalshabToolbar.styles.js
> +      color: '#EDF4F5',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabToolbar/RecordCircle/RecordCircle.jsx
> +  </svg>
you can create svg file instead with the css from the other file inside.

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Malshab/MalshabToolbar/interviewFormat.util.js
> +const interviewDurationStrFormat = (startDate) => {
create util folder and add this file to it (widthout `.util.js `ending)

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/Notesbox/Notesbox.styles.js
> +    backgroundColor: '#ffffff12',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/ProgressStepper.jsx
> +          <StyledStepLabel StepIconComponent={QontoStepIcon} style={{ whiteSpace: 'pre-line' }}>
ass to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/ProgressStepper.styles.js
> +    color: '#ffffffa6',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/ProgressStepper.styles.js
> +    color: '#00AFCC',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/ProgressStepper.utils.js
> +import moment from 'moment';
add to utils folder as well

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/Qonto/Qonto.styles.js
> +    color: '#eaeaf0',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/Qonto/Qonto.styles.js
> +    color: '#00AFCC',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/Qonto/Qonto.styles.js
> +    borderColor: '#eaeaf0',
get from theme

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/AmericanAnswer/AmericanAnswer.jsx
> +              style={{ direction: 'rtl' }}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/AmericanAnswer/AmericanAnswer.jsx
> +              style={{ color: '#02aecd' }}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/AmericanAnswer/AmericanAnswer.jsx
> +          label={<span style={{ fontSize: '1rem' }}>{option}</span>}
add to className

2021-07-20 15:53 UTC, carmeltsadok commented on src/common/Questionnaire/Question/AmericanAnswer/AmericanAnswer.jsx
> +              style={{ color: '#02aecd' }}
add to className

2021-07-21 08:55 UTC, AdarPascal commented on src/pages/InterviewDashboard/components/ProgressBar/ProgressStepper/Qonto/Qonto.styles.js
> +    borderColor: '#eaeaf0',
This color doesnt exist in theme and show up in the app files only here

2021-07-21 09:33 UTC, AdarPascal commented on src/common/Questionnaire/Question/Question.styles.js
> +    '& > div > button': { color: '#02aecd' },
not in palette

2021-07-21 10:10 UTC, carmeltsadok approved these changes

2021-07-21 10:14 UTC, lustigy96 approved these changes

2021-07-21 10:14 UTC, lustigy96 commented on mockserver/index.js
> +    apiUri: 'http://localhost:7071',
```suggestion
    apiUri: 'http://localhost:${config.port}',
```

2021-07-21 10:14 UTC, merged