Fix Loaders Timing
alphayesodot/itur-client pull request #89
Opened 2021-07-25 10:52 UTC by PCOffline

2021-07-25 12:57 UTC, carmeltsadok approved these changes

2021-07-25 12:57 UTC, carmeltsadok commented on src/pages/Reports/index.jsx
> +    const timeout = setTimeout(() => setIsLoading(true), 1000);
add it on more loaders :) like track page etc..

2021-07-25 13:02 UTC, PCOffline commented on src/pages/Reports/index.jsx
> +    const timeout = setTimeout(() => setIsLoading(true), 1000);
On some pages it shows a message that there are no items, and starts loading only after a second.. It can be confusing to the user

2021-07-25 13:02 UTC, PCOffline commented on src/pages/Reports/index.jsx
> +    const timeout = setTimeout(() => setIsLoading(true), 1000);
But I'll inspect other pages. I'm working on the questionnaire right now

2021-07-28 09:56 UTC, carmeltsadok approved these changes

2021-08-24 11:38 UTC, Delitefully requested changes

2021-08-24 11:38 UTC, Delitefully commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireOptionsButton/QuestionnaireOptionsButton.jsx
> +  const handleDelete = () => setQuestionnaireToDelete({ ...questionnaire }) || console.log('deleting!');
console.log

2021-08-24 11:56 UTC, carmeltsadok approved these changes

2021-08-24 12:09 UTC, PCOffline commented on src/pages/QuestionnaireSchemaPage/components/QuestionnaireOptionsButton/QuestionnaireOptionsButton.jsx
> +  const handleDelete = () => setQuestionnaireToDelete({ ...questionnaire }) || console.log('deleting!');
console.no

2021-08-24 12:10 UTC, merged