export to users to excel
alphayesodot/itur-client pull request #91
Opened 2021-07-25 15:05 UTC by maykremer

2021-07-25 17:07 UTC, carmeltsadok requested changes

2021-07-25 17:07 UTC, carmeltsadok commented on src/common/ExportToExcel/ExportToExcel.jsx
> +    <div>
not required

2021-07-25 17:13 UTC, carmeltsadok requested changes

2021-07-25 17:13 UTC, carmeltsadok commented on src/pages/UserManagement/components/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> -import usersImg from '../../../../utils/images/userManagement/users.png';
if you had to remove the icons, delete them from the images folder as well

2021-07-26 07:33 UTC, lustigy96 approved these changes

2021-07-26 07:33 UTC, lustigy96 commented on src/pages/UserManagement/components/UnitDetailsHeadLine/UnitDetailsHeadLine.jsx
> -import usersImg from '../../../../utils/images/userManagement/users.png';
agreed

2021-07-27 08:22 UTC, merged