Malshabim schedule fix bugs add remove all
alphayesodot/itur-client pull request #97
Opened 2021-07-28 08:43 UTC by vitaly-furman

2021-07-28 09:59 UTC, carmeltsadok requested changes

2021-07-28 09:59 UTC, carmeltsadok commented on src/pages/MalshabSchedule/components/MalshabimCard/MalshabimCard.jsx
> +    return interviewersObjects.map(({ name }) => `מ${name.split(' ')[1] ?? name.slice(-3)}`).join(',');
get letter `מ` from i18n

2021-07-28 09:59 UTC, carmeltsadok commented on src/pages/MalshabSchedule/index.jsx
> +    if (availableInterviwers.length > 0) {
```suggestion
    if (availableInterviwers.length) {
```

2021-07-28 09:59 UTC, carmeltsadok commented on src/pages/MalshabSchedule/index.jsx
> +      const addedInterviewer = await EventService.addInterviewer(malshabEvent.id, selectedInterviewer.id);
add `.catch` in case there is an error and toast an error message

2021-07-28 09:59 UTC, carmeltsadok commented on src/pages/MalshabSchedule/index.jsx
>          selectedInterviewer.id);
add .catch

2021-08-01 13:21 UTC, vitaly-furman commented on src/pages/MalshabSchedule/index.jsx
> +      const addedInterviewer = await EventService.addInterviewer(malshabEvent.id, selectedInterviewer.id);
the .catch is in the handleMalshabsToShedule functions, after Promise.all.

2021-08-01 13:32 UTC, AdarPascal approved these changes

2021-08-01 13:33 UTC, merged